all:
  children:
    jellyfin_lxc_hosts:
      hosts:
        pepper:
          ansible_host: 10.0.1.12
          ansible_user: root
    pbs:
      hosts:
        pbs01:
          ansible_host: 10.0.1.20
          ansible_user: debian
    docker_hosts:
      hosts:
        docker01:
          ansible_host: 10.0.1.21
          ansible_user: debian
    jellyfin_hosts:
      hosts:
        jellyfin01:
          ansible_host: 10.0.1.22
          ansible_user: root
